### ISSUE TITLE
Keyboard closes on Notefox Android

### ISSUE THREAD

**Issue by 9jS2PL5T** [Sav22999/websites-notes#112]
Hi, today i was creating a note using Notefox on Firefox Android. While typing the note, the keyobard was forcing to close several times. Can you recreate that?

**Comment by Sav22999** [comment]
@9jS2PL5T I cannot replicate this issue, can you give me more details. For example, if it's not private, the website where the issue happens and some other information.
Thanks 😄

**Comment by 9jS2PL5T** [comment]
What kind of other information do you need?
Seems like a specific website doesn't matter. It happens on any website to me.

**Comment by Sav22999** [comment]
Some details which can help me to get the bug: OS version, Firefox version.
Can you give me the steps to reproduce the bug?
E.g.
1. Open website XYZ
2. ...
3. I get the issue

**Comment by 9jS2PL5T** [comment]
Android 11
Firefox 128.0.1
1. Open website XYZ (really 😉) 
2. I get the issue

**Comment by 9jS2PL5T** [comment]
https://github.com/user-attachments/assets/80917e39-1211-4b82-b817-0d6ef6f35953

**Comment by Sav22999** [comment]
@9jS2PL5T Thank you for the recording. I'll check and fix asap.

Sorry for this inconvenience, in the meanwhile

**Comment by Sav22999** [comment]
@9jS2PL5T Fixed in the 4.1.0.3

**Comment by 9jS2PL5T** [comment]
Thanks for your work, but I'm still having this issue with 4.1.0.3 :/

**Comment by Sav22999** [comment]
@9jS2PL5T  oh no 😢

I cannot understand what's the problem...
I'll try to check better, sorry for the inconvenience
